/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @file Defines the data models used for interacting with the backend API.
 * It includes interfaces that represent the structure of requests and responses
 * exchanged between the Angular application and the API endpoints.
 */

/**
 * Represents a request to the Veo video generation API.
 */
export interface VeoGenerateVideoRequest {
  /**
   * The prompt to provide to Veo.
   */
  prompt: string;
  /**
   * A base64-encoded image to use in the generated video.
   */
  image?: string;
}

/**
 * Represents the response from the Veo video generation API.
 */
export interface VeoGenerateVideoResponse {
  /**
   * The name of the operation used to track the video generation process.
   */
  operation_name: string;
}

/**
 * Represents a video generated by Veo.
 */
export interface Video {
  /**
   * The URI of the video.
   */
  uri: string;
  /**
   * The encoding of the video.
   */
  encoding: string;
  /**
   * The signed URL for accessing the video.
   */
  signed_uri: string;
}

/**
 * Represents a request to the Veo operation status API.
 */
export interface VeoGetOperationStatusRequest {
  /**
   * The name of the operation to get the status of.
   */
  operation_name: string;
}

/**
 * Represents a response from the Veo operation status API.
 */
export interface VeoGetOperationStatusResponse {
  /**
   * The name of the operation.
   */
  name: string;
  /**
   * Whether the operation is done.
   */
  done: boolean;
  /**
   * The list of videos, if the operation is done.
   */
  videos: Video[] | null;
}
