# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""The model definitions for the backend API."""
import pydantic


class VeoGenerateVideoRequest(pydantic.BaseModel):
  """Represents a request to the Veo video generation API.

  Attributes:
    prompt: The prompt to provide to Veo.
    image: A base64-encoded image to use in the generated video.
  """
  prompt: str
  image: str | None = None


class VeoGenerateVideoResponse(pydantic.BaseModel):
  """Represents a response from the Veo video generation API.

  Attributes:
    operation_name: The name of the operation used to track the video generation
      process.
  """
  operation_name: str


class Video(pydantic.BaseModel):
  """Represents a video generated by Veo.

  Attributes:
    uri: The URI of the video.
    encoding: The encoding of the video.
  """
  uri: str
  encoding: str


class VideoSample(pydantic.BaseModel):
  """Represents a single video sample in the operation status response.

  Attributes:
      video: The video object.
  """
  video: Video


class GeneratedSamples(pydantic.BaseModel):
  """Represents a list of videos in the operation status response.

  Attributes:
      generated_samples: The list of video samples.
  """
  generated_samples: list[VideoSample]


class VeoGetOperationStatusRequest(pydantic.BaseModel):
  """Represents a request to the Veo operation status API.

  Attributes:
    operation_name: The name of the operation to get the status of.
  """
  operation_name: str


class VeoGetOperationStatusResponse(pydantic.BaseModel):
  """Represents a response from the Veo operation status API.

  Attributes:
    name: The name of the operation.
    done: Whether the operation is done.
    response: The response from the operation, if it is done.
  """
  name: str
  done: bool
  response: GeneratedSamples | None = None

