# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Placeholder functions for interacting with Vertex AI."""


def generate_video_from_veo() -> str:
  """Generates a video from Veo based on a prompt.

  Returns:
    The path to the generated video file, or None if generation failed.
  """
  return '/'


def generate_voice_over_script() -> str:
  """Generates the script to use in voice-over that follows ABCD best practices.

  Using Gemini in Vertex AI, generate a script for the voice over.

  Returns:
    The script for the voice-over.
  """
  prompt = """
    You are a script writer for the advertising industry.
    I am a retailer selling the Google Pixel 9 pro phone.
    I would like to drive people to the Google store to buy my phone.
    I am creating a 6 second advert that shows the phone,
    and I need a script that I can use to create a voice over on top of it.
    The video will be 6 seconds long, and needs to follow our ABCD best
    practices:
    A - Attract Attention from the Start: No matter the format, it's crucial
        to capture attention early on.
    B - Brand Naturally With Purpose: How and when branding appears can impact
        the performance of brand lift metrics.
    C - Connect Through Emotion & Storytelling: Longer watch time is associated
        with a lift in brand awareness and consideration.
    D - Direct the Viewer What to do Next: Clear calls to action drive brand
        lift.
    Output only the words that should be read, no other words should be
    included.
  """
  print(prompt)
  return 'Placeholder script generated by Gemini.'
